### ISSUE TITLE
Long documents

### ISSUE THREAD

**Issue by larsboldt** [Rias500/craft-scout#12]
Is there any plans to support long documents? We currently exceed the limits of algolia row size (20kb) and Algolia refers to https://www.algolia.com/doc/guides/ranking/distinct/#distinct-to-index-large-records

Our problem comes from trying to index text fields added to a matrix field, we dont know how many text fields are added, and as such, they may exceed the limit. 

My initial plan was to add support for splitting up an article in accordance to the link above, but thought I'd check if this was something that was already thought of in this plugin or a planned feature?

**Comment by Rias500** [comment]
This is not something that's built in to the plugin and I currently don't have plans for it either as it's not something I need.

I'll gladly accept a PR to add this feature though if you're planning to implement this 👍

**Comment by larsboldt** [comment]
Ok, I will look into how to best solve this and submit a PR once/if I get a satisfactory solution.
