### ISSUE TITLE
Skip entry

### ISSUE THREAD

**Issue by matevisky** [Rias500/craft-scout#15]
Is it possible to skip entry somehow, and not from the criteria query, but from the transformer view?

I have been tried to return null, but it failed, also tried to return empty array, which is not working either.

In some cases I need more complex logic, what I really would like to put algolia, and what not...

Thank you for the great, and free product!

**Comment by Rias500** [comment]
I'm not entirely sure how to do this, I was thinking maybe adding a check for returning false in the transformer that makes it skip the entry.

How would you like to have this work?

**Comment by matevisky** [comment]
Ok, the dream specification should be the following:
 - I can send back the array
 - I can skip it returning null
 - Or I can force deletion with flagging maybe the array?

The reason is simple. Maybe I would like to rotate out (too old item, or it is not relevant anymore) from the searchindex something, but It will be not deleted on my side. If I am sending null, it will be remain in the search index.
If I am sending the item, it will be still remain (i do not want it either)

Maybe the best pratice would be some kind of action field on the array, which has a default value like "upsert" but also can hold "delete" or "null".
If it is null, than we do not have to push it, otherwise we have to push it with the action

I created a wish about this one

**Comment by matevisky** [comment]
Now you can support this Wish from https://beerpay.io/Rias500/craft-scout/wishes/5ae8c06c5c3b5105c0652456

🍻 Cheers!

**Comment by Rias500** [comment]
So I've thought about this and will not be implementing it. It will make everything very unpredictable and more complicated than necessary.

If you want elements to be excluded from the index you could add a field on them like a flag and include this in your mapping criteria:

```
'criteria' => [
     'section' => 'blog',
    'yourField' => true,
],
```

This way if you run the index again it will remove or add the element like you want. Skipping is not wise as your Algolia index should always be a reflection of the state your entries are in.

**Comment by matevisky** [comment]
Hey @Rias500 thank for considering this change. My "issue" is the following maybe you have a better workaround. My ultimate goal would be able to send and index an action which tell is the element is deleted or not.

So Maybe it is existing in Craft, and maybe it is not deleted from craft, but when I am pushing it out to algolia I would like to mark it for deletion. Can you consider this scenario?

Like this we are not skipping anything from the logic, but we have a freedom not only customize the fields, but also the "action" as well?

**Comment by Rias500** [comment]
> So Maybe it is existing in Craft, and maybe it is not deleted from craft, but when I am pushing it out to algolia I would like to mark it for deletion. Can you consider this scenario?

You can if you just have a field that you set to true/false and include it in the criteria. Then when you save the index is run again and the entry will then be deleted. You don't need to delete it from Craft, just have a field that is included in the criteria.

**Comment by Rias500** [comment]
I'll reopen because I think this can be solved differently without adding extra complexity with "actions". I'll have to think about it.

**Comment by matevisky** [comment]
thx appreciate your effort!

Mate
+64 27 9783981

**Comment by Rias500** [comment]
So I've tested this again, and adding filters to your criteria will cause Scout to deindex when the element cannot be found with the criteria.

See https://github.com/Rias500/craft-scout/issues/18
