### ISSUE TITLE
Can you create a functionality to disable autosync?

### ISSUE THREAD

**Issue by matevisky** [Rias500/craft-scout#16]
Hi @Rias500 

I would appriciate a functionality to disable the auto save functionality of the package. Lots of change is going on, so we are updating the index daily in a bulk mode. So it would be nice to just load the env and disable the event listener for save by flag.

Like this it would be supereasy to manage when to save the index

Thank you for your help and great work!

**Comment by matevisky** [comment]
Also we would definitely by and support this package if it would go for a paid version. It is a great help for us.

**Comment by Rias500** [comment]
I've added a `sync` setting to the config in the new release which allows you to disable automatic indexing of elements.

In regards to the paid version, I don't have the legal requirements to do this within my country, I'd have to set up a registered company for this and would cost me more than I'd earn from a few plugins.

On top of that keeping it open source means it's open for other contributors to add functionality that I don't need but which I'm happy to support.

You can always support me by donating through [Beerpay](https://beerpay.io/Rias500/craft-scout).

**Comment by matevisky** [comment]
Sweet, thx. Quick question about this. If I am delete an item, what is happening? will the importer load, and force delete the item, or it will be skipped?

**Comment by Rias500** [comment]
All automatic actions will be disabled, so deleting as well.

**Comment by matevisky** [comment]
That is fine, but my question is more like, when I am running

`./craft scout/index/import searchall`

Will it automatically run on every item, even if it was get deleted or not?

**Comment by Rias500** [comment]
Yes, it will run on all items that are found using the criteria in the config.
