### ISSUE TITLE
Consider renaming scout/index/import

### ISSUE THREAD

**Issue by timkelty** [Rias500/craft-scout#20]
I initially was confused by `scout/index/import`, as it wasn't clear if I was importing _into_ Craft (which I realize you wouldn't ever do…), or into Algolia.

At any rate, if not renaming, perhaps just clarifying in the task command desc (adding _to Algolia_ or _from Craft_ or something)

**Comment by Rias500** [comment]
I've updated the descriptions, but since it's such a small change I'm not yet tagging a release for it.
