### ISSUE TITLE
FR: batch uploads to Algolia

### ISSUE THREAD

**Issue by timkelty** [Rias500/craft-scout#23]
Often saving an entry with many relations can cause A LOT of operations to Algolia, which is more expensive, and takes longer.

Ideally, operations would be batched, using: https://www.algolia.com/doc/api-reference/api-methods/batch/

**Comment by Rias500** [comment]
The current architecture of the plugin and how it's setup with the Craft queues would require a big rewrite to do this, if it's even possible.

There would need to be some way to collect all the entries that would need to be updated, batch them into algolia but then also prevent their usual indexing events from happening when they're saved. 

This will probably not be something that will make it into this plugin
