### ISSUE TITLE
Duplicate jobs should not be added to the queue

### ISSUE THREAD

**Issue by timkelty** [Rias500/craft-scout#24]
![screen shot 2018-07-24 at 12 34 50 pm](https://user-images.githubusercontent.com/18329/43153119-69e8394e-8f3e-11e8-99e0-4c36bc410b2a.png)

The queue should first be checked if the elementId you are indexing already exists in the queue

**Comment by Rias500** [comment]
It doesn't seem possible to get this information back from the queue. I'd try and find the source of the multiple jobs being triggered and try to mitigate that
