### ISSUE TITLE
Assets Transform?

### ISSUE THREAD

**Issue by Lennso** [Rias500/craft-scout#28]
Hi,

i use your great plugin but i'm not familiar with php. I want to add a data field to my mapping so that i can get the img url. i think i have to combine two criteria models or? Can you please give me a hint?

`"mappings" => [
				[
						'indexName' => 'xyz',
						'elementType' => \craft\elements\Entry::class,
						'criteria' => [
								'section' => 'xyz'
						],
						'transformer' => function(craft\elements\Entry $entry) {
							return [
									'title' => $entry->title,
									'id' => $entry->id,
									'uri' => $entry->uri,
									'url' => $entry->url,
									'slug' => $entry->slug,
									'enabled' => $entry->enabled,
									'archived' => $entry->archived,
									'postDate' => $entry->postDate,
									'dateCreated' => $entry->dateCreated,
									'dateUpdated' => $entry->dateUpdated,
									'expiryDate' => $entry->expiryDate,
									'hero' => $entry->heroImage
							];
						}
				],
    ],`

**Comment by Rias500** [comment]
If you use a transformer, you can add the image field and the crops you want:

```php
[
            'indexName' => 'blog',
            'elementType' => \craft\elements\Entry::class,
            'criteria' => [
                'section' => 'blog',
            ],
            'transformer' => function (\craft\elements\Entry $element) {
                return [
                    'title' => $element->title,
                    'thumbnail' => $element->image->one()->getUrl([
                        'width' => 300,
                        'height' => 300,
                    ]),
                ];
            },
        ],
```
