### ISSUE TITLE
De-indexing not working from entries index page. 

### ISSUE THREAD

**Issue by JamesNuttall** [Rias500/craft-scout#33]
It seems deleting an entry from the entries index page, like below, does not de-index the entry:

![screen shot 2018-10-09 at 16 33 37](https://user-images.githubusercontent.com/22011451/46680534-36aa2300-cbe1-11e8-9387-b924dad85bc6.png)

**Comment by Rias500** [comment]
Cannot reproduce this anymore, can you check if this is still the case in the latest version? If it is you can re-open this issue.
