### ISSUE TITLE
Exception when saving custom element

### ISSUE THREAD

**Issue by elvdm** [Rias500/craft-scout#4]
### Description
When saving a custom element type added with a different plugin, an exception is thrown. This only happens while Scout is installed.

`Serialization of 'Closure' is not allowed`

Does not seem to matter whether the element is new or not. This issue was not happening prior to upgrading to Craft 3-RC9.

### Steps to reproduce

1. Install and enable the Scout plugin.
2. Try to save a custom element i.e. not any element types provided out of the box with Craft.
3. Error :(

### Additional info
Craft version: 3-RC9 (Pro)
PHP version: 7.1

In my logs:
```
2018-02-06 19:07:47 [127.0.0.1][1][v9ve9k2fd9d1cm6l7mpmvdu5il][error][Exception] Exception: Serialization of 'Closure' is not allowed in /Users/emma/Sites/bouwjobs/vendor/yiisoft/yii2-queue/src/serializers/PhpSerializer.php:24
Stack trace:
#0 [internal function]: ArrayObject->serialize()
#1 /Users/emma/Sites/bouwjobs/vendor/yiisoft/yii2-queue/src/serializers/PhpSerializer.php(24): serialize(Object(rias\scout\jobs\IndexElement))
#2 /Users/emma/Sites/bouwjobs/vendor/yiisoft/yii2-queue/src/Queue.php(159): yii\queue\serializers\PhpSerializer->serialize(Object(rias\scout\jobs\IndexElement))
#3 /Users/emma/Sites/bouwjobs/vendor/craftcms/cms/src/queue/Queue.php(148): yii\queue\Queue->push(Object(rias\scout\jobs\IndexElement))
#4 /Users/emma/Sites/bouwjobs/vendor/rias/craft-scout/src/Scout.php(70): craft\queue\Queue->push(Object(rias\scout\jobs\IndexElement))
#5 [internal function]: rias\scout\Scout->rias\scout\{closure}(Object(craft\events\ModelEvent))
#6 /Users/emma/Sites/bouwjobs/vendor/yiisoft/yii2/base/Event.php(221): call_user_func(Object(Closure), Object(craft\events\ModelEvent))
#7 /Users/emma/Sites/bouwjobs/vendor/yiisoft/yii2/base/Component.php(565): yii\base\Event::trigger('craft\\base\\Elem...', 'afterSave', Object(craft\events\ModelEvent))
#8 /Users/emma/Sites/bouwjobs/vendor/craftcms/cms/src/base/Element.php(1718): yii\base\Component->trigger('afterSave', Object(craft\events\ModelEvent))
#9 /Users/emma/Sites/bouwjobs/plugins/bouwjobsstripe/src/elements/Plan.php(553): craft\base\Element->afterSave(true)
#10 /Users/emma/Sites/bouwjobs/vendor/craftcms/cms/src/services/Elements.php(478): dadamotion\bouwjobsstripe\elements\Plan->afterSave(true)
#11 /Users/emma/Sites/bouwjobs/plugins/bouwjobsstripe/src/controllers/PlansController.php(127): craft\services\Elements->saveElement(Object(dadamotion\bouwjobsstripe\elements\Plan), false)
#12 [internal function]: dadamotion\bouwjobsstripe\controllers\PlansController->actionSave()
#13 /Users/emma/Sites/bouwjobs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/emma/Sites/bouwjobs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /Users/emma/Sites/bouwjobs/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('save', Array)
#16 /Users/emma/Sites/bouwjobs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#17 /Users/emma/Sites/bouwjobs/vendor/craftcms/cms/src/web/Application.php(241): yii\base\Module->runAction('bouwjobs-stripe...', Array)
#18 /Users/emma/Sites/bouwjobs/vendor/craftcms/cms/src/web/Application.php(451): craft\web\Application->runAction('bouwjobs-stripe...', Array)
#19 /Users/emma/Sites/bouwjobs/vendor/craftcms/cms/src/web/Application.php(212): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /Users/emma/Sites/bouwjobs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /Users/emma/Sites/bouwjobs/web/index.php(42): yii\base\Application->run()
#22 /Users/emma/.composer/vendor/laravel/valet/server.php(133): require('/Users/emma/Sit...')
#23 {main}
```

**Comment by Rias500** [comment]
Hi! Can you provide me with the exact mapping you're using for the entries? Then I can try to replicate the issue you're having

**Comment by Rias500** [comment]
So I've been able to track down the issue, and it has to do with how Yii serializes jobs before pushing them onto the queue, you're using a conditional validator in your element which uses a closure and closures can't be serialized into a queue.

```
$rules[] = ['handle', 'unique', 'on' => 'update', 'when' => function($model) {
    return $model->isAttributeChanged('handle');
}];
```

There's some solutions [here](https://github.com/yiisoft/yii2/issues/4883#issuecomment-54029353) and [here][https://github.com/yiisoft/yii2/issues/7773) that could be of help.

**Comment by matevisky** [comment]
Is there any better workaround for this? The problem is many:

It is not working at all if we have clouser of any entry
I am not able to say explicitly what try to push to algolia, because the mapping logic is after the queue and not before
So maybe it would be better to put the mapping logic before the queue push, also it could avoid the clouser issue I guess and would give us the freedom to skip the not mapped Entries.

Please let me know if you do not have time to do it or to check it, I know it is a big change. Thank you for the great code anyway!!! Greatly appreciated!

**Comment by Rias500** [comment]
@matevisky In the new version I try to serialize it, and if it doesn't work just index it straight away. So that solves the issue if you really need a closure.

I'll think on improving this in the future.

**Comment by matevisky** [comment]
Thank. Speaking frankly the filter functionality is also needed badly before putting everything into the queue. Right it is not working at all. Anyhow I will troubleshoot which custom field is causing the issue, and will let you know
Can I ask what is your plan to publish the new version? weeks/months? Thank you!

**Comment by Rias500** [comment]
This is a plugin mostly for my use case, that's why it's free and open source, if you need other functionality you can always submit a PR or fork it. And I'll consider it. Otherwise I'll adapt this plugin if my needs change in the future, I don't have an estimate for this.

If you need more flexibility and support, you might want to wait for Topshelfcraft to port the Search Plus plugin.

**Comment by Rias500** [comment]
@matevisky https://github.com/Rias500/craft-scout/releases/tag/0.3.0 restructures how indexing with the Queue works, it should be improved a lot now and not rely on serialization too much.
