### ISSUE TITLE
Unknown command: scout/index/import

### ISSUE THREAD

**Issue by JMDevelopers** [Rias500/craft-scout#48]
Has the import command changed or am i missing something? Seems not be able to find the command

**Comment by dbrookes** [comment]
Same issue for me, after upgrading to 1.1.0 none of the scout console commands are available anymore. Downgrading back to 1.0.2 brings them back.

**Comment by philipzaengle** [comment]
This seems to be an OS specific problem, running the command in an OSX terminal fails, additionally running `./craft` returns only native Craft commands. 

When running one of these commands in ubuntu everything works as expected. YMMV

**Comment by philipzaengle** [comment]
I've submitted a PR #49 which corrects this issue.
