### ISSUE TITLE
Entry removed on update

### ISSUE THREAD

**Issue by u12206050** [Rias500/craft-scout#57]
I have sync enabled in config, but whenever I update an entry it is removed from Algolia.
From the queue status in the side bar I see it tries to do the following:

* Removes the entry
* Adds the entry
* Removes the entry

See the attached image.

<img width="420" alt="skjermbilde 2019-02-25 kl 15 52 16" src="https://user-images.githubusercontent.com/6641242/53345564-80d43c80-3915-11e9-8c49-8c1b238f493e.png">

**Comment by Rias500** [comment]
Could you post the criteria you are using and your index settings?

**Comment by jasonschock** [comment]
I'm having this issue, as well. Not sure if it's a bug or unexpected behavior.

I have multiple mappings in my Scout config for the *same* index, which is a nice way to break up indexing for different types of content by section.

`scout.php`:

```php
return [
    "sync" => true,
    "connect_timeout" => 5,
    "application_id" => $app_id,
    "admin_api_key" => $api_key,
    "mappings" => [
        // Blog channel
        [
            'indexName' => $index_name,
            'elementType' => \craft\elements\Entry::class,
            'criteria' => [
                'section' => 'blog',
            ],
            'transformer' => function (craft\base\Element $element) {
                $res = transformCommonProperties($element);
                return $res;
            },
        ],

        // Events channel
        [
            'indexName' => $index_name,
            'elementType' => \craft\elements\Entry::class,
            'criteria' => [
                'section' => 'events',
            ],
            'transformer' => function (craft\base\Element $element) {
                $res = transformCommonProperties($element);
                $res['content'] = [
                    'overview' => $element->eventOverview,
                    'date' => $element->eventDate,
                    'endTime' => $element->eventEndTime
                ];
                return $res;
            },
        ],
    ]
];
```

Assuming the above config, when I save a **blog** entry, I see two operations in Algolia:
* A POST with the updated entry data (expected)
* A DELETE for the entry that was just updated (not expected)

![Indices___Algolia](https://user-images.githubusercontent.com/27365/54710128-415bd300-4b04-11e9-91da-912585465439.png)

If I comment out the Events config section and only have the Blog config, then it behaves as expected, i.e. no DELETE call happens.

So it seems like for every additional mapping that I have, there will be a DELETE call. E.g.
given config:
```php
    "mappings" => [
        // Blog channel for dev_index
        // Events channel for dev_index
        // Pages structure for dev_index
        // Structure X for  dev_index
    ]
```

When I update a blog entry, in Algolia I'll see:

* POST /1/indexes/dev_main
* DELETE /1/indexes/dev_main/1_304
* DELETE /1/indexes/dev_main/1_304
* DELETE /1/indexes/dev_main/1_304

The behavior isn't what I expect. I don't want anything deleted, unless I delete something in Craft.

If this is not the correct way to break up mappings for a single index, what is?

**Comment by Rias500** [comment]
@jasonschock You can only have one mapping for each index, a way you could solve this is by changing your criteria to just pull the entries from both sections, this is what your config would look like:

```php
return [
    "sync" => true,
    "connect_timeout" => 5,
    "application_id" => $app_id,
    "admin_api_key" => $api_key,
    "mappings" => [
        [
            'indexName' => $index_name,
            'elementType' => \craft\elements\Entry::class,
            'criteria' => [
                'section' => ['blog', 'events'],
            ],
            'transformer' => function (craft\base\Element $element) {
                $res = transformCommonProperties($element);

                if ($element->section->handle === 'events') {
                    $res['content'] = [
                        'overview' => $element->eventOverview,
                        'date' => $element->eventDate,
                        'endTime' => $element->eventEndTime
                    ];
                }

                return $res;
            },
        ],
    ]
];
```

**Comment by Rias500** [comment]
Supporting multiple mappings for the same index would require too big of a rewrite and everything you need to do if you want to have multiple sections in the same index can be done in your transformer. Just make sure the `criteria` allow for it.

**Comment by jasonschock** [comment]
Thanks @Rias500, that's how I ended up solving it. FWIW, I think being able to break up the index is a bit more elegant and intuitive, but maybe not everyone has this need.
