### ISSUE TITLE
Algolia Application ID and Admin API key as twig variables

### ISSUE THREAD

**Issue by jamesmacwhite** [Rias500/craft-scout#59]
Hi @Rias500,

Thanks for this plugin. I am currently looking at migrating a previous Algolia search mapping setup from Search Plus using your plugin. One thing that would be nice is to have Algolia admin API key and application ID exposed as twig variables so they output in Twig templates when building the front end search i.e.

```
{{ craft.scout.algoliaApplicationId }}
{{ craft.scout.algoliaAdminApiKey }}
```

Would this be something you be happy to have added to your plugin?

**Comment by Rias500** [comment]
Great idea! I’ll work on it when I find some time, otherwise I’ll gladly accept a PR
