### ISSUE TITLE
Does this work with Commerce products/variants?

### ISSUE THREAD

**Issue by fantasticmachine** [Rias500/craft-scout#65]
Hi

Can you tell me if the plugin will work with Commerce products and variants?

**Comment by Rias500** [comment]
Scout listens to any `Element` that gets updated, as Commerce products and variants extends this, it should pick up the necessary events.

Make sure to use the correct ElementType in your config and it should work, though I have not tested it myself.

**Comment by fantasticmachine** [comment]
Excellent, thank you.
I’ll give it a go and report back.

**Comment by fantasticmachine** [comment]
Hi
Yep works great!
I'm actually indexing variants with some data pertaining to the parent product.

But I do have another problem which I'll raise in another issue
