### ISSUE TITLE
Can't install with trendyminds/algolia

### ISSUE THREAD

**Issue by fantasticmachine** [Rias500/craft-scout#66]
During development I have had Scout installed alongside another plugin (trendyminds/algolia) which was handling the actual search on my site.

But now I'm trying to install the same plugins elsewhere and finding that I can't have both Scout and Alogolia installed together. There seems to be a conflict between the versions of algolia/algoliasearch-client-php

Scout requires 1.28.0 but Algoila requires ^2.2
With Scout installed I get the following message when trying to install Algolia

> Problem 1
>     - Installation request for trendyminds/algolia ^2.0 -> satisfiable by trendyminds/algolia[2.0.0].
>     - Conclusion: remove algolia/algoliasearch-client-php 1.28.0
>     - Conclusion: don't install algolia/algoliasearch-client-php 1.28.0
>     - trendyminds/algolia 2.0.0 requires algolia/algoliasearch-client-php ^2.2 -> satisfiable by algolia/algoliasearch-client-php[2.2.0, 2.2.1, 2.2.2, 2.2.3].
>     - Can only install one of: algolia/algoliasearch-client-php[2.2.0, 1.28.0].
>     - Can only install one of: algolia/algoliasearch-client-php[2.2.1, 1.28.0].
>     - Can only install one of: algolia/algoliasearch-client-php[2.2.2, 1.28.0].
>     - Can only install one of: algolia/algoliasearch-client-php[2.2.3, 1.28.0].
>     - Installation request for algolia/algoliasearch-client-php (locked at 1.28.0) -> satisfiable by algolia/algoliasearch-client-php[1.28.0].

I can't find a way around this. Is there some way to change the requirement for Scout?

**Comment by Rias500** [comment]
I'd have to change the version constraint and test everything with the new Algolia major version. I'm guessing some APIs have changed or have been deprecated.

I'll try to find some time in the coming week to update this. If this has any breaking changes it'll require a major release of craft-scout as well.

**Comment by fantasticmachine** [comment]
Understood. Is there any way I can get around it temporarily?

**Comment by Rias500** [comment]
Should be fixed in 1.2.0, not a lot of changes were necessary
