### ISSUE TITLE
1.2 release not available on Packagist

### ISSUE THREAD

**Issue by jamesmacwhite** [Rias500/craft-scout#68]
Hi @Rias500. Just to let you know that the recent 1.2 release isn't available to install through composer. Looks like packagist has not been updated yet. The update is detected through Craft plugin store, but composer can't see it.

Thanks!

**Comment by Rias500** [comment]
I've updated it manually on Packagist, hsould be available now!

**Comment by jamesmacwhite** [comment]
Many thanks!
