### ISSUE TITLE
Nothing getting indexed

### ISSUE THREAD

**Issue by larsboldt** [Rias500/craft-scout#8]
./craft scout/index/import
Adding elements from index .[===============] 100% (0/0) ETA: n/a

scout.php
return [
    'application_id' => '...',
    'admin_api_key' => '...',
    'mappings' => [
        [
            'indexName' => 'poc_magasin',
            'elementType' => \craft\elements\Entry::class,
            'criteria' => [
                'section' => 'cityPlanningArticles'
            ],
            'transformer' => function (craft\base\Element $element) {
                return $element->toArray();
            },
        ],
    ],
];

Nothing in the logs that says much about what is happening, or not happening.

**Comment by Rias500** [comment]
Are you sure you're using the correct section handle and that they're all published?

**Comment by larsboldt** [comment]
Yes, this code gives me all articles for the same section:
{% set entries = craft.entries.section('cityPlanningArticles').all() %}

**Comment by Rias500** [comment]
I cannot seem to reproduce this, it must be something with the section you defined, could you post a screenshot of the section settings and the content? Maybe I can find something wrong with them then.

**Comment by larsboldt** [comment]
![skjermbilde 2018-03-20 kl 12 06 39](https://user-images.githubusercontent.com/201756/37651087-3e74dafc-2c37-11e8-9b99-d3f7c88c742d.png)

What content do you mean?

**Comment by Rias500** [comment]
I've just tried everything with the same settings and it works for me.

Does this return something when you try it from a module or plugin?

`\craft\elements\Entry::find()->section('cityPlanningArticles')->all();` this is what Scout runs in the background to find the entries.

**Comment by larsboldt** [comment]
It does.

**Comment by larsboldt** [comment]
This is the query... returns zero elements.

`craft\elements\db\EntryQuery Object
(
    [editable] => 
    [sectionId] => Array
        (
            [0] => 1
        )

    [typeId] => 
    [authorId] => 
    [authorGroupId] => 
    [postDate] => 
    [before] => 
    [after] => 
    [expiryDate] => 
    [defaultOrderBy:protected] => Array
        (
            [entries.postDate] => 3
        )

    [elementType] => craft\elements\Entry
    [query] => 
    [subQuery] => 
    [contentTable] => {{%content}}
    [customFields] => 
    [inReverse] => 
    [asArray] => 
    [id] => 
    [uid] => 
    [fixedOrder] => 
    [status] => Array
        (
            [0] => live
        )

    [archived] => 
    [dateCreated] => 
    [dateUpdated] => 
    [siteId] => 
    [enabledForSite] => 1
    [relatedTo] => 
    [title] => 
    [slug] => 
    [uri] => 
    [search] => 
    [ref] => 
    [with] => 
    [orderBy] => 
    [withStructure] => 1
    [structureId] => 
    [level] => 
    [ancestorOf] => 
    [ancestorDist] => 
    [descendantOf] => 
    [descendantDist] => 
    [siblingOf] => 
    [prevSiblingOf] => 
    [nextSiblingOf] => 
    [positionedBefore] => 
    [positionedAfter] => 
    [_result:craft\elements\db\ElementQuery:private] => 
    [_resultCriteria:craft\elements\db\ElementQuery:private] => 
    [_searchScores:craft\elements\db\ElementQuery:private] => 
    [select] => Array
        (
            [0] => **
        )

    [selectOption] => 
    [distinct] => 
    [from] => 
    [groupBy] => 
    [join] => 
    [having] => 
    [union] => 
    [params] => Array
        (
        )

    [queryCacheDuration] => 
    [queryCacheDependency] => 
    [_events:yii\base\Component:private] => Array
        (
        )

    [_eventWildcards:yii\base\Component:private] => Array
        (
        )

    [_behaviors:yii\base\Component:private] => Array
        (
            [customFields] => craft\behaviors\ElementQueryBehavior Object
                (
                    [altText] => 
                    [article] => 
                    [articleFeedbackEmail] => 
                    [attribution] => 
                    [description] => 
                    [files] => 
                    [filteredMatrixContent] => 
                    [flowContent] => 
                    [image] => 
                    [images] => 
                    [imageText] => 
                    [linkText] => 
                    [linkUrl] => 
                    [logo] => 
                    [mainArticle] => 
                    [mainImages] => 
                    [mainQuote] => 
                    [matrixContent] => 
                    [month01] => 
                    [month02] => 
                    [month03] => 
                    [month04] => 
                    [month05] => 
                    [month06] => 
                    [month07] => 
                    [month08] => 
                    [month09] => 
                    [month10] => 
                    [month11] => 
                    [month12] => 
                    [pageTitle] => 
                    [prioritized] => 
                    [projectTitle] => 
                    [quote] => 
                    [quoteArticle] => 
                    [relatedServices] => 
                    [richTextField] => 
                    [seo] => 
                    [snippet] => 
                    [source] => 
                    [subLogoTextFirst] => 
                    [subLogoTextSecond] => 
                    [summary] => 
                    [tagBusiness] => 
                    [tagEditorial] => 
                    [tagSubject] => 
                    [targetMethodNew] => 
                    [targetText] => 
                    [targetUrl] => 
                    [text] => 
                    [textAuthor] => 
                    [textForMainPage] => 
                    [textTitle] => 
                    [transcription] => 
                    [urlForMainPage] => 
                    [vimeoLink] => 
                    [_customFieldValues:craft\behaviors\ContentBehavior:private] => Array
                        (
                        )

                    [owner] => craft\elements\db\EntryQuery Object
 *RECURSION*
                )

        )

    [where] => 
    [limit] => 
    [offset] => 
    [indexBy] => 
    [emulateExecution] => 
)`

**Comment by Rias500** [comment]
The only filter on there is `sectionId => 1` and `status => live`, I have no idea why it wouldn't return anything.

**Comment by larsboldt** [comment]
Debugging the queryBuilder I found this:

´´´[where] => Array
                        (
                            [0] => and
                            [1] => Array
                                (
                                    [0] => or
                                    [1] => Array
                                        (
                                            [0] => =
                                            [1] => entries.sectionId
                                            [2] => 1
                                        )

                                )

                            [2] => Array
                                (
                                    [elements_sites.siteId] => 4
                                )

                            [3] => Array
                                (
                                    [content.siteId] => 4
                                )``
`

We are running a multi-site setup, and siteId 4 is the main site, but not where the articles of section "cityPlanningArticles" are located. Those are located in siteId 1 in our case... siteId must be determined by which site is enabled for a section I guess and that might not be whats happening here? If multiple sites are enabled for a section they should all be listed in the where part of the query?

**Comment by Rias500** [comment]
@larsboldt Ah, that makes sense, I think most use cases would call for seperate indexes for each site, so you could do the following in your mappings:

```
[
    'indexName' => 'poc_magasin_1',
    'elementType' => \craft\elements\Entry::class,
    'criteria' => [
        'section' => 'cityPlanningArticles',
        'siteId' => 1
    ],
    'transformer' => function (craft\base\Element $element) {
        return $element->toArray();
    },
],
[
    'indexName' => 'poc_magasin_2',
    'elementType' => \craft\elements\Entry::class,
    'criteria' => [
        'section' => 'cityPlanningArticles',
        'siteId' => 2
    ],
    'transformer' => function (craft\base\Element $element) {
        return $element->toArray();
    },
],
...
```
